gotenberg:
  enabled: true
  name: gotenberg

  image: 452336408843.dkr.ecr.us-west-2.amazonaws.com/gotenberg-fips:latest
  imagePullPolicy: Always

  service:
    name: sw-gotenberg
    port: 3500
    annotations: {}
    labels: {}

  serviceAccountName: ""

  podAnnotations: {}
  labels: {}
  resources: {}

  nodeSelector:
    kubernetes.io/arch: amd64

  tolerations: []
  affinity: {}

  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1001
    seccompProfile:
      type: RuntimeDefault

  command:
    - gotenberg

  args:
    - "--chromium-deny-list=^file:///[^tmp].*|169.254.169.254.*"
    - "--api-timeout=120s"
    - "--api-port=3500"
    - "--pdfengines-disable-routes=true"
    - "--webhook-disable=true"
    - "--prometheus-disable-collect=true"
    - "--prometheus-disable-route-logging=true"

chrome:
  enabled: false
  name: chrome

  image: selenium/standalone-chrome:143.0
  imagePullPolicy: IfNotPresent

  service:
    name: chrome
    port: 4444
    annotations: {}
    labels: {}
